steps:
  - name: ':terraform: Provision ECS'
    command: '/.buildkite/terraform-ecs.sh'
    branches: 'develop staging master'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: terraform
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
    agents:
      queue: 'elastic'

  - name: ':terraform: Provision Elastic Beanstalk Application'
    command: '/.buildkite/terraform-ebapplication.sh'
    branches: 'develop staging master'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: terraform
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
    agents:
      queue: 'elastic'

  - name: ':terraform: Provision VPC'
    command: '/.buildkite/terraform-vpc.sh'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: terraform
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
    agents:
      queue: 'elastic'        

  - wait

  - name: ':hammer: Build'
    command: '/.buildkite/build.sh'
    branches: 'develop staging master'
    agents:
      queue: 'elastic' 

  - name: ':fire: Test'
    command: '/.buildkite/test.sh'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
    branches: 'develop staging master'  
    agents:
      queue: 'elastic'

  - wait

  - name: ':rocket: Deploy'
    command: '/.buildkite/deploy.sh'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
    branches: 'develop staging master'
    agents:
      queue: 'elastic'   