steps:
  - name: ':hammer::fire: Build and Test'
    command: '/.buildkite/test.sh'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
    branches: 'develop staging'  
    agents:
      queue: 'elastic'

  - wait

  - name: ':rocket: Deploy'
    command: '/.buildkite/deploy.sh'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
    branches: 'develop staging master'
    agents:
      queue: 'elastic'